using System;
using System.Collections.ObjectModel;
using System.Data.SqlClient;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.ServiceModel.Dispatcher;
using System.Threading.Tasks;
using YardTracker.Contracts;

namespace YardTracker.Service
{
    internal static class Log
    {
        private static readonly object Gate = new object();

        public static void Info(string message) => Write(ConsoleColor.Gray, "INFO ", message);
        public static void Ok(string message) => Write(ConsoleColor.Green, "OK   ", message);
        public static void Warn(string message) => Write(ConsoleColor.Yellow, "WARN ", message);

        public static void Error(string message, Exception? exception = null) =>
            Write(ConsoleColor.Red, "ERROR", exception == null ? message : message + Environment.NewLine + exception);

        private static void Write(ConsoleColor color, string level, string message)
        {
            lock (Gate)
            {
                var previous = Console.ForegroundColor;
                Console.ForegroundColor = color;
                Console.WriteLine($"{DateTime.Now:HH:mm:ss.fff} {level} {message}");
                Console.ForegroundColor = previous;
            }
        }
    }

    /// <summary>A request the caller must fix. Returned to the client as a "Validation" fault.</summary>
    internal sealed class ServiceValidationException : Exception
    {
        public ServiceValidationException(string message) : base(message) { }
    }

    internal static class Guard
    {
        public static string Required(string? value, string name, int maxLength)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new ServiceValidationException($"{name} is required.");

            var trimmed = value!.Trim();
            if (trimmed.Length > maxLength)
                throw new ServiceValidationException($"{name} cannot be longer than {maxLength} characters.");
            return trimmed;
        }

        public static string? Optional(string? value, string name, int maxLength) =>
            string.IsNullOrWhiteSpace(value) ? null : Required(value, name, maxLength);

        public static Guid NotEmpty(Guid value, string name)
        {
            if (value == Guid.Empty)
                throw new ServiceValidationException($"{name} must be a non-empty GUID generated by the client.");
            return value;
        }

        public static T NotNull<T>(T? value, string name) where T : class =>
            value ?? throw new ServiceValidationException($"{name} is required.");

        public static int Clamp(int value, int min, int max) => Math.Max(min, Math.Min(max, value));

        /// <summary>Default (unset) timestamps mean "use server time"; local times are converted to UTC.</summary>
        public static DateTime? Utc(DateTime? value)
        {
            if (value == null || value.Value == default)
                return null;
            return value.Value.Kind == DateTimeKind.Local ? value.Value.ToUniversalTime() : DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
        }
    }

    /// <summary>
    /// Wraps every service operation: timing, logging, and translation of exceptions into typed
    /// <see cref="FaultException{ServiceFault}"/>s so stack traces never reach the client.
    /// </summary>
    internal static class Operation
    {
        public static async Task<T> Run<T>(string operation, string detail, Func<Task<T>> body, Func<T, string>? describe = null)
        {
            var name = operation.EndsWith("Async", StringComparison.Ordinal) ? operation.Substring(0, operation.Length - 5) : operation;
            var stopwatch = Stopwatch.StartNew();
            try
            {
                var result = await body().ConfigureAwait(false);
                var summary = describe?.Invoke(result);
                var line = $"{name,-20} {detail}{(summary == null ? "" : " -> " + summary)} ({stopwatch.ElapsedMilliseconds} ms)";
                if (summary != null && summary.StartsWith("Rejected", StringComparison.Ordinal))
                    Log.Warn(line);
                else
                    Log.Info(line);
                return result;
            }
            catch (ServiceValidationException ex)
            {
                Log.Warn($"{name,-20} {detail} -> invalid request: {ex.Message}");
                throw Fault("Validation", ex.Message, null);
            }
            catch (SqlException ex) when (ex.Number >= 50000 && ex.Number < 51000)
            {
                // Business rule raised with THROW in a stored procedure.
                Log.Warn($"{name,-20} {detail} -> {ex.Message}");
                throw Fault("Rejected", ex.Message, null);
            }
            catch (SqlException ex)
            {
                var correlationId = NewCorrelationId();
                Log.Error($"{name,-20} {detail} -> database error [{correlationId}]", ex);
                throw Fault("Unavailable", "The inventory database is unavailable. Try again shortly.", correlationId);
            }
            catch (Exception ex) when (!(ex is FaultException))
            {
                var correlationId = NewCorrelationId();
                Log.Error($"{name,-20} {detail} -> unexpected error [{correlationId}]", ex);
                throw Fault("Internal", "Unexpected server error. Reference " + correlationId + ".", correlationId);
            }
        }

        public static Task Run(string operation, string detail, Func<Task> body) =>
            Run(operation, detail, async () =>
            {
                await body().ConfigureAwait(false);
                return true;
            });

        private static FaultException<ServiceFault> Fault(string code, string message, string? correlationId) =>
            new FaultException<ServiceFault>(
                new ServiceFault { Code = code, Message = message, CorrelationId = correlationId ?? string.Empty },
                new FaultReason(message),
                new FaultCode(code));

        private static string NewCorrelationId() => Guid.NewGuid().ToString("N").Substring(0, 12);
    }

    /// <summary>Last-resort logger for errors raised outside operations (serialization, channel faults).</summary>
    internal sealed class UnhandledErrorLogger : IServiceBehavior, IErrorHandler
    {
        public void ApplyDispatchBehavior(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase)
        {
            foreach (ChannelDispatcherBase dispatcher in serviceHostBase.ChannelDispatchers)
                ((ChannelDispatcher)dispatcher).ErrorHandlers.Add(this);
        }

        public void AddBindingParameters(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase,
            Collection<ServiceEndpoint> endpoints, BindingParameterCollection bindingParameters)
        {
        }

        public void Validate(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase)
        {
        }

        public bool HandleError(Exception error)
        {
            if (!(error is FaultException) && !(error is CommunicationException))
                Log.Error("Unhandled WCF error", error);
            return error is FaultException;
        }

        public void ProvideFault(Exception error, MessageVersion version, ref Message fault)
        {
        }
    }
}
