/* =============================================================================
   YardTracker — 04_seed.sql
   Reference data: sites, locations, operators, stations, products, trucks,
   machines. Inventory and history are generated by the simulator:
       dotnet run --project src/YardTracker.Simulator -- backfill --days 60
   ============================================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

INSERT dbo.Sites (SiteCode, Name, Latitude, Longitude, TimeZoneId) VALUES
    ('NYD', N'North Yard',                 29.941500, -95.398200, 'Central Standard Time'),
    ('SYD', N'South Yard',                 29.648300, -95.207400, 'Central Standard Time'),
    ('CTP', N'Coating & Threading Plant',  29.793100, -95.073600, 'Central Standard Time');

INSERT dbo.Locations (SiteId, LocationCode, Name, LocationType, CapacityTons)
SELECT s.SiteId, v.LocationCode, v.Name, v.LocationType, v.CapacityTons
FROM (VALUES
    ('NYD', 'NYD-DOCK1', N'Receiving Dock 1',        'Dock',        140),
    ('NYD', 'NYD-R01',   N'Pipe Rack 01',            'Rack',        180),
    ('NYD', 'NYD-R02',   N'Pipe Rack 02',            'Rack',        180),
    ('NYD', 'NYD-R03',   N'Casing Rack 03',          'Rack',        260),
    ('NYD', 'NYD-R04',   N'Tubing Rack 04',          'Rack',        210),
    ('NYD', 'NYD-LD-A',  N'Laydown Area A',          'Laydown',     450),
    ('NYD', 'NYD-LD-B',  N'Laydown Area B',          'Laydown',     450),
    ('NYD', 'NYD-QA',    N'QA Hold / Quarantine',    'Quarantine',  80),
    ('NYD', 'NYD-STG',   N'Outbound Staging',        'Staging',     150),
    ('SYD', 'SYD-DOCK1', N'Receiving Dock 1',        'Dock',        80),
    ('SYD', 'SYD-R01',   N'Plate & Beam Rack 01',    'Rack',        160),
    ('SYD', 'SYD-R02',   N'Bar Stock Rack 02',       'Rack',        90),
    ('SYD', 'SYD-LD-A',  N'Laydown Area A',          'Laydown',     500),
    ('SYD', 'SYD-QA',    N'QA Hold / Quarantine',    'Quarantine',  50),
    ('SYD', 'SYD-STG',   N'Outbound Staging',        'Staging',     150),
    ('CTP', 'CTP-DOCK1', N'Plant Receiving Dock',    'Dock',        80),
    ('CTP', 'CTP-BAY1',  N'Coating Line Bay',        'Bay',         90),
    ('CTP', 'CTP-BAY2',  N'Threading Bay',           'Bay',         70),
    ('CTP', 'CTP-FG',    N'Finished Goods Rack',     'Rack',        200),
    ('CTP', 'CTP-STG',   N'Outbound Staging',        'Staging',     120)
) AS v (SiteCode, LocationCode, Name, LocationType, CapacityTons)
JOIN dbo.Sites AS s ON s.SiteCode = v.SiteCode;

INSERT dbo.Operators (BadgeNumber, DisplayName, Role, IsActive) VALUES
    ('1001', N'Maria Alvarez',   'Operator',   1),
    ('1002', N'James Carter',    'Operator',   1),
    ('1003', N'Tom Nguyen',      'Operator',   1),
    ('1004', N'Aisha Patel',     'Operator',   1),
    ('1005', N'Sam Whitaker',    'Operator',   1),
    ('2001', N'Dana Brooks',     'Supervisor', 1),
    ('3001', N'Luis Romero',     'Driver',     1),
    ('3002', N'Kevin O''Neil',   'Driver',     1),
    ('1099', N'Former Employee', 'Operator',   0);

INSERT dbo.Stations (StationCode, Name, DeviceType, DefaultLocationId)
SELECT v.StationCode, v.Name, v.DeviceType, l.LocationId
FROM (VALUES
    ('HH-01',      N'Handheld 01 (North Yard receiving)', 'Handheld',    'NYD-DOCK1'),
    ('HH-02',      N'Handheld 02 (North Yard laydown)',   'Handheld',    'NYD-LD-A'),
    ('HH-03',      N'Handheld 03 (South Yard)',           'Handheld',    'SYD-DOCK1'),
    ('HH-04',      N'Handheld 04 (Plant)',                'Handheld',    'CTP-DOCK1'),
    ('HH-DRV1',    N'Driver handheld (trucks)',           'Handheld',    NULL),
    ('PORTAL-N1',  N'North Yard gate RFID portal',        'FixedReader', 'NYD-STG'),
    ('KIOSK-SHIP', N'Shipping office kiosk',              'Kiosk',       'NYD-STG')
) AS v (StationCode, Name, DeviceType, DefaultLocationCode)
LEFT JOIN dbo.Locations AS l ON l.LocationCode = v.DefaultLocationCode;

INSERT dbo.Products (ProductCode, Category, Description, Grade, OuterDiameterIn, WallThicknessIn, NominalLengthFt, WeightLbsPerFt) VALUES
    ('PIPE-X52-1275', 'Pipe',   N'Line pipe 12.75" OD x 0.375" WT, bevelled',  'API 5L X52', 12.750, 0.375, 40.00, 49.560),
    ('PIPE-X65-1600', 'Pipe',   N'Line pipe 16" OD x 0.500" WT, bevelled',     'API 5L X65', 16.000, 0.500, 40.00, 82.770),
    ('PIPE-B-0663',   'Pipe',   N'Seamless pipe 6.625" OD x 0.280" WT',        'A106 Gr B',   6.625, 0.280, 21.00, 18.970),
    ('CSG-P110-0700', 'Casing', N'Casing 7" 29 ppf, LTC',                      'API 5CT P110', 7.000, 0.408, 40.00, 29.000),
    ('CSG-J55-0963',  'Casing', N'Casing 9-5/8" 36 ppf, BTC',                  'API 5CT J55',  9.625, 0.352, 40.00, 36.000),
    ('TBG-L80-0288',  'Tubing', N'Tubing 2-7/8" 6.5 ppf, EUE',                 'API 5CT L80',  2.875, 0.217, 31.50,  6.500),
    ('TBG-N80-0350',  'Tubing', N'Tubing 3-1/2" 9.3 ppf, EUE',                 'API 5CT N80',  3.500, 0.254, 31.50,  9.300),
    ('PLT-A36-0500',  'Plate',  N'Plate 1/2" x 96" wide',                      'ASTM A36',     NULL,  0.500, 20.00, 163.360),
    ('BM-W12X26',     'Beam',   N'Wide flange beam W12x26',                    'ASTM A992',    NULL,  NULL,  40.00, 26.000),
    ('BAR-1018-0200', 'Bar',    N'Cold drawn round bar 2" dia',                'AISI 1018',    2.000, NULL,  12.00, 10.680);

INSERT logistics.Trucks (TruckCode, Description, MaxPayloadLbs) VALUES
    ('TRK-101', N'Flatbed tractor-trailer #101', 48000),
    ('TRK-102', N'Flatbed tractor-trailer #102', 48000),
    ('TRK-201', N'Pole trailer (long pipe) #201', 45000);

INSERT telemetry.MachineStatuses (StatusCode, StatusName) VALUES
    (0, 'Offline'), (1, 'Idle'), (2, 'Running'), (3, 'Fault'), (4, 'Maintenance');

INSERT telemetry.Machines (MachineCode, Name, MachineType, LocationId, ModbusUnitId, TempWarnC, TempAlarmC)
SELECT v.MachineCode, v.Name, v.MachineType, l.LocationId, v.UnitId, v.WarnC, v.AlarmC
FROM (VALUES
    ('CRN-N1', N'North Yard overhead crane 1 (hoist motor)', 'Crane',       'NYD-LD-A', 1,  85.0, 100.0),
    ('SAW-C1', N'Band saw, cut line',                        'Saw',         'CTP-BAY2', 2,  70.0,  85.0),
    ('OVN-C1', N'Coating line cure oven',                    'CoatingOven', 'CTP-BAY1', 3, 245.0, 260.0),
    ('THR-C1', N'CNC pipe threader',                         'Threader',    'CTP-BAY2', 4,  65.0,  80.0)
) AS v (MachineCode, Name, MachineType, LocationCode, UnitId, WarnC, AlarmC)
JOIN dbo.Locations AS l ON l.LocationCode = v.LocationCode;

EXEC rpt.usp_EnsureDimDate '2025-01-01', '2027-12-31';
GO
