<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>YardTracker.Simulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YardTracker.Client\YardTracker.Client.csproj" />
    <ProjectReference Include="..\YardTracker.Modbus\YardTracker.Modbus.csproj" />
  </ItemGroup>

</Project>
